### PR TITLE
Github handle made optional

### PR DESCRIPTION
**Pull request by Parth-Vader**
Github handle made optional in the form.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@nitinkgp23 @DefCon-007 Is it optional in flask?

**Comment by DefCon-007** [comment]
@OrkoHunter I have to make the change in the database. And no checking is done on the flask side it just pushes data.
Also, I think after keeping the GitHub handle optional a simple message asking the user to register on GitHub will look good.

**Comment by OrkoHunter** [comment]
Agreed. Something like `Optional, but recommended` ?

**Comment by DefCon-007** [comment]
Yes and are making a login interface ?

**Comment by OrkoHunter** [comment]
Did not get you.

**Comment by DefCon-007** [comment]
Like a "Student" can log in to edit details and maybe check few things. The main aim will be to add GitHub handle later.

**Comment by OrkoHunter** [comment]
That might be tricky. We'll simply keep it `contact us` basis. Write an email and we'll add/fix it.

**Comment by OrkoHunter** [comment]
Also, instead of `handle`, please write `username` in placeholder.

**Comment by DefCon-007** [comment]
Don't you that's a hectic thing. What say we keep it mandatory because GitHub account IS mandatory for KWoC. 
Lets give instructions to register on GitHub if someone leaves it blank

**Comment by Parth-Vader** [comment]
@OrkoHunter Should I also add (Optional, but recommended)?

**Comment by OrkoHunter** [comment]
Okay so added a `link to sign up` beside the text box or under it referencing  https://github.com/join?source=header-home

**Comment by OrkoHunter** [comment]
@Parth-Vader No, just change it to `GitHub username` and read my last comment.

**Comment by DefCon-007** [comment]
We can show that link only when someone leaves that field blank

**Comment by OrkoHunter** [comment]
That too.

**Comment by DefCon-007** [comment]
Ok updating the issue

**Pull request closed without merging**
