### PR TITLE
Using send grid to send mails

### PR DESCRIPTION
**Pull request by DefCon-007**

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@DefCon-007 Great work ! Is it working fine?

**Comment by DefCon-007** [comment]
@OrkoHunter : Yup it is. You can check by registering yourself or a project.

**Comment by OrkoHunter** [comment]
Working fine. How does sendgrid work with gmail then, no SMTP ?

**Comment by DefCon-007** [comment]
I guess so.

**Pull request merged**
