### PR TITLE
Timer and Color Fix

### PR DESCRIPTION
**Pull request by AvijitGhosh82**

### CODE REVIEW

**Comment by OrkoHunter** [comment]
A snapshot alongside would be helpful I think. :)

**Comment by AvijitGhosh82** [comment]
This is just code cleaning : P

**Comment by DefCon-007** [comment]
@OrkoHunter We can now run locally

**Comment by OrkoHunter** [comment]
Okay then!

**Comment by DefCon-007** [comment]
@AvijitGhosh82 : Lets not merge it now you can use this PR only to change the colours and all of the website

**Comment by OrkoHunter** [comment]
@AvijitGhosh82 Great work here !

**Pull request merged**
