### PR TITLE
Added notification for successful submission of form / error

### PR DESCRIPTION
**Pull request by nitinkgp23**
This PR needs testing. 
Possible issue : 
app.py sends 'msgcode' to index.html , but its value doesn't change. Its value is 0 always, even if it is initialised as some other value ( 1 or 2 or 3 ) in line no. 38

Due to this, the error message always corresponds to msgcode=0 .

### CODE REVIEW

**Comment by kshitij10496** [comment]
@nitinkgp23 I think `flash` will be more suitable here. 
Just import this function from flask and write the CSS.

**Comment by nitinkgp23** [comment]
I just fixed this. And this is working fine now.

**Comment by kshitij10496** [comment]
Instead of passing a `msgcode`, we can simply flash the `msg` to notify a registration.
It will hardly take 5 mins to modify the code.

**Comment by OrkoHunter** [comment]
Let's see once for sweetalert.

**Pull request merged**
